-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 10:10:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearning` DEFAULT CHARACTER SET utf8 ;
USE `elearning` ;

-- -----------------------------------------------------
-- Table `elearning`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `useremail` VARCHAR(128) NOT NULL,
  `userpassword` VARCHAR(256) NOT NULL,
  `roll` INT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `useremail_UNIQUE` (`useremail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`wordlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`wordlist` (
  `idwordlist` INT NOT NULL AUTO_INCREMENT,
  `listname` VARCHAR(45) NOT NULL,
  `createdate` DATE NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idwordlist`),
  UNIQUE INDEX `idwordlist_UNIQUE` (`idwordlist` ASC) VISIBLE,
  INDEX `fk_wordlist_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_wordlist_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `elearning`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`score` (
  `idscore` INT NOT NULL AUTO_INCREMENT,
  `score` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `wordlist_idwordlist` INT NOT NULL,
  PRIMARY KEY (`idscore`),
  UNIQUE INDEX `idscore_UNIQUE` (`idscore` ASC) VISIBLE,
  INDEX `fk_score_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_score_wordlist1_idx` (`wordlist_idwordlist` ASC) VISIBLE,
  CONSTRAINT `fk_score_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `elearning`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_wordlist1`
    FOREIGN KEY (`wordlist_idwordlist`)
    REFERENCES `elearning`.`wordlist` (`idwordlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`words` (
  `idwords` INT NOT NULL AUTO_INCREMENT,
  `englishword` VARCHAR(45) NOT NULL,
  `translatedword` VARCHAR(45) NOT NULL,
  `wordlist_idwordlist` INT NOT NULL,
  PRIMARY KEY (`idwords`),
  UNIQUE INDEX `idwords_UNIQUE` (`idwords` ASC) VISIBLE,
  INDEX `fk_words_wordlist1_idx` (`wordlist_idwordlist` ASC) VISIBLE,
  CONSTRAINT `fk_words_wordlist1`
    FOREIGN KEY (`wordlist_idwordlist`)
    REFERENCES `elearning`.`wordlist` (`idwordlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
